openapi: 3.0.0
info:
  title: Category Management API
  description: This API allows clients to manage categories in a hierarchical structure for event organization.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /categories:
    post:
      tags:
        - Categories
      summary: Add a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                parent_id:
                  type: integer
                  format: int64
                  nullable: true
      responses:
        "201":
          description: Successfully created category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          description: Invalid input

  /categories/{id}:
    delete:
      tags:
        - Categories
      summary: Remove a category by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Successfully deleted category
        "400":
          description: Invalid input
        "404":
          description: Category not found

  /categories/top-level:
    get:
      tags:
        - Categories
      summary: Fetch top-level categories
      responses:
        "200":
          description: An array of top-level categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"

  /categories/{id}/subtree:
    get:
      tags:
        - Categories
      summary: Fetch a subtree of categories starting from the specified parent ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: An array of categories within the subtree
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        "400":
          description: Invalid input
        "404":
          description: Category not found

  /categories/{id}/parent:
    patch:
      tags:
        - Categories
      summary: Move a category to a new parent
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_parent_id:
                  type: integer
                  format: int64
      responses:
        "200":
          description: Successfully moved the category
        "400":
          description: Invalid input
        "404":
          description: Category not found

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        parent_id:
          type: integer
          format: int64
          nullable: true
